server:
  port: 10000
wushig:
  elastic:
    enable: true
    hostName: ***
    port: 9200
  log:
    enable: true
    enableController: true
    enableAnnotation: true
    RecordLogClassInfo: myLogSaver